### ISSUE TITLE
[meta] UX/UI improvements

### ISSUE THREAD

**Issue by schickling** [graphcool/dashboard#125]
- [ ] Create core concept
- [ ] Redesign field popup
- [ ] Take a look at the Relation Popup hint animation 
- [ ] DateTime Lists seem to be malformatted
- [ ] Project settings page

**Comment by marktani** [comment]
Some suggestions for the Relation Popup:
You could autofill the field names depending on the selection of one/many and the models like this:
![relation-popup](https://cloud.githubusercontent.com/assets/1780597/17642882/2dd7971c-6158-11e6-9a63-0ec16b681de3.png)

If the user changes the `Todo` selection to `User` for example, the `todo` field should be automatically renamed to `user`.

Also, I think the list brackets `[]`should be surrounding the `comments` field in this example, rather than
the `Comment` model.
