### ISSUE TITLE
data browser: [meta]

### ISSUE THREAD

**Issue by sorenbs** [graphcool/dashboard#132]
- [x] Editing a field value shouldn't require a double but a single click
- [x] Clicking tab on the keyboard should move cursor to next column
- [x] When in the last column, tabbing should move focus to ADD then CANCEL buttons and you should be able to press enter to add or cancel
- [x] Clicking ADD NODE should put the cursor in the first column
- [x] Clicking enter should save the new node
- [x] Clicking ESC on the keyboard should have the same effect as clicking CANCEL
- [x] AddRow is not on top
- [x] Popups are not shown correctly
- [x] Headers vanish when resizing
- [x] Replace AddRow with special renderer
- [x] NodeSelector doesn't work with onClick
- [x] Editing a popup should change the value when you're back at the data browser
- [x] in adding mode the cells keep focus after blurring
- [ ] pressing tab in NodeSelector doesn't blur the cell
- [x] row shouldn't reload when no changes were made
- [ ] refine string field behavior (default single line - when newline character, expand to textarea)
- [x] investigate filter behavior when adding new value
- [x] scrolling + refreshing should maintain the same position

@schickling Do you agree?

**Comment by brene** [comment]
@sorenbs 
> Clicking enter should save the new node

This could result in accidental adding, since the user also uses enter to save a field
> Clicking esc on the keyboard should have same effect as clicking CANCEL

same with this one. Image a user fills 20 fields and then mistakenly presses ESC
@julianbauer what is your take on this?

**Comment by brene** [comment]
@sorenbs I would need an API te tell me the total length of the filtered list to make it work if our infinite scroller. Is this something you can arrange?
