### ISSUE TITLE
[meta] RelationsPopup redesign

### ISSUE THREAD

**Issue by brene** [graphcool/dashboard#167]
- [x] description at the wrong place at first
- [x] field names shouldn't be visible when models not set
- [x] proper padding/margin
- [x] make second model selection transparent if the first model hasn't been selected yet
- [x] show name input field when both models have been selected
- [x] prepopulate field names
- [x] Help text in the helper tabs should be updated
- [x] remove tada
- [x] adjust popup header to distinguish between new/edit relation
- [x] list: edit relation by clicking on row
- [x] generated mutations
- [ ] more help messages up top
- [ ] darker text color because it's hard to read @julianbauer 
- [x] list: represent multiple models with new UI
