### ISSUE TITLE
[meta] Getting Started Issues

### ISSUE THREAD

**Issue by brene** [graphcool/dashboard#217]
- [x] check that the fields `imageUrl` and `description` are created
- [x] create & validate steps: `STEP2_ENTER_FIELD_NAME_IMAGEURL`, `STEP2_SELECT_TYPE_IMAGEURL`, `STEP2_CLICK_CONFIRM_IMAGEURL`
- [x] check that the playgroud requests has been sent
- [x] make the 1st playground popup scrollable
- [x] send `example` payload
- [x] make sure that polling of example starting works
- [x] make the div of `STEP5_DONE` scrollable
- [x] polling doesn't work 100%
- [x] Switching to Data Browser in "Switch to the Data Browser" step does not trigger an update
- [x] starting the field creation by entering the correct field name but then cancelling the field popup doesn't update the step appropriately
