### ISSUE TITLE
[meta] Relations editor

### ISSUE THREAD

**Issue by schickling** [graphcool/dashboard#94]
- [x] Design list of all relations
- [x] Design relation create/edit details view (Popup?)
- [x] Implement list of all relations
- [x] Implement relation create details view
- [x] Implement relation edit details view
- [x] Seperate relation fields from other fields
- [x] Adjust fields popup to work with new relations
- [x] Optimize usability

**Comment by schickling** [comment]
First draft for list of relations:

![relations - overview](https://cloud.githubusercontent.com/assets/1567498/17473780/9fa869ac-5d52-11e6-8550-d3c3e5a262c2.png)

**Comment by brene** [comment]
@julianbauer can you export all the icons for me? Preferably, allow me to be able to set the color of the icons by setting the fill. Otherwise we would need to set different styles for different icons.
